name = "internal"
main = "src/index.ts"
compatibility_date = "2024-12-24"

compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "file-bucket"

[[d1_databases]]
binding = "DB"
database_name = "doc2md"
database_id = "063da939-422e-498f-978b-c84c5bcc6f65"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1